In [1]:
import numpy as np
import pandas as pd

In [10]:
input_values = np.array([[0,0],[0,1],[1,1],[1,0]])
input_values.shape
input_values

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

In [11]:
output = np.array([0,1,1,0])
output.reshape(4,1)
output

array([0, 1, 1, 0])

In [12]:
weights = np.array([[0.1],[0.2]])
weights

array([[0.1],
       [0.2]])

In [13]:
bias = 0.3

In [14]:
def sigmoid_fun(x):
  return 1/(1 + np.exp(-x))

In [15]:
def der(x):
  return sigmoid_fun(x)*(1-sigmoid_fun(x))

In [16]:
for i in range(10000):
  input_arr = input_values

  weighed_sum = np.dot(input_arr,weights) + bias
  first_output = sigmoid_fun(weighed_sum)
  error = first_output - output
  total_error = np.square(np.subtract(first_output,output)).mean()

  first_der = error
  second_der = der(first_output)
  derivate = first_der*second_der

  t_input = input_values.T
  final_derivative = np.dot(t_input,derivate)

  weights = weights - 0.05*final_derivative

  for i in derivate:
    bias = bias - 0.05*i
  
  print(weights)
  print(bias)

Streaming output truncated to the last 5000 lines.
 [-1.88625849  1.8790851   1.8790851  -1.88625849]]
[-7.4339731   7.20793307  7.20793307 -7.4339731 ]
[[-1.9154305   1.84806038  1.84806038 -1.9154305 ]
 [-1.88625977  1.87908639  1.87908639 -1.88625977]]
[-7.43398285  7.20794278  7.20794278 -7.43398285]
[[-1.91543175  1.8480617   1.8480617  -1.91543175]
 [-1.88626106  1.87908768  1.87908768 -1.88626106]]
[-7.43399261  7.20795249  7.20795249 -7.43399261]
[[-1.915433    1.84806302  1.84806302 -1.915433  ]
 [-1.88626234  1.87908896  1.87908896 -1.88626234]]
[-7.43400236  7.2079622   7.2079622  -7.43400236]
[[-1.91543425  1.84806435  1.84806435 -1.91543425]
 [-1.88626363  1.87909025  1.87909025 -1.88626363]]
[-7.43401211  7.20797192  7.20797192 -7.43401211]
[[-1.91543551  1.84806567  1.84806567 -1.91543551]
 [-1.88626491  1.87909154  1.87909154 -1.88626491]]
[-7.43402187  7.20798163  7.20798163 -7.43402187]
[[-1.91543676  1.84806699  1.84806699 -1.91543676]
 [-1.88626619  1.87909283  1.87